name: "Build and push to Cachix"
on:
  push:
    branches:
      - nix-config
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - nixosConfigurations.odin.config.system.build.toplevel
          - nixosConfigurations.thor.config.system.build.toplevel
          - homeConfigurations.odin.activationPackage
          - homeConfigurations.thor.activationPackage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: chadac-dotfiles
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build ${{ matrix.target }}
        run: nix build --print-build-logs ".#${{ matrix.target }}"
